name: insta_post_maker
description: Instagram post generator from text

version: 1.0.0+5

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver_v3: ^1.0.0
  google_fonts: ^5.1.0
  permission_handler: ^10.4.0
  flutter_bloc: ^8.1.3
  screenshot: ^2.1.0
  auto_size_text: ^3.0.0
  logger: ^1.4.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/testing_text