name: insta_post_maker
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver: ^1.7.0
  google_fonts: 2.1.0
  permission_handler: ^8.1.6
  flutter_bloc: ^7.3.0
  screenshot: 1.2.3
  path_provider: ^2.0.5
  get: 4.3.8
  auto_size_text: ^2.1.0
  uuid: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  lorem_ipsum_nonrandom: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true