name: insta_post_maker
description: Instagram post generator from text

version: 1.0.0+4

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver_v3: ^1.0.0
  google_fonts: ^4.0.3
  permission_handler: ^10.2.0
  flutter_bloc: ^8.1.2
  screenshot: ^1.3.0
  auto_size_text: ^3.0.0
  logger: ^1.3.0
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lorem_ipsum_nonrandom: ^1.0.1
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true